auth:
  existingSecret: postgres-postgresql
  database: app_db

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30007

persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"