auth:
  postgresPassword: "{{ requiredEnv "POSTGRES_PASSWORD" }}"

postgres:
  database: "{{ .Environment.Values.postgres.database }}"

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: NodePort
  port: 5432
  nodePort: 30007