server:
  enabled: true
  image:
    tag: "1.15.5"

  extraEnvironmentVars:
    VAULT_ADDR: http://127.0.0.1:8200

  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }

      storage "raft" {
        path    = "/vault/data"
        node_id = "vault-node-1"
      }

      service_registration "kubernetes" {}

  service:
    type: NodePort
    nodePort: 30080  # UI доступен на этом порту

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: vault.java-mp.space
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - secretName: vault-tls
        hosts:
          - vault.java-mp.space

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  persistence:
    enabled: true
    storageClass: "local-path"
    size: 5Gi