environments:
  dev:
    values:
      - environments/dev/values.yaml

---
releases:
  - name: postgres
    namespace: dev
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.7.8
    values:
      - values/postgres-values.yaml
      - environments/dev/values.yaml

  - name: vault
    namespace: dev
    chart: hashicorp/vault
    version: 0.27.0
    values:
      - values/vault-values.yaml
      - environments/dev/values.yaml