repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: runix
    url: https://helm.runix.net
  - name: external-secrets
    url: https://charts.external-secrets.io

environments:
  dev:
    values:
      - environments/dev/postgres-values.yaml

---
releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.14.3
    values:
      - values/cert-manager-values.yaml

  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.9.17
    values:
      - environments/dev/external-secrets-values.yaml

  - name: postgres
    namespace: dev
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 16.7.8
    values:
      - values/postgres-values.yaml
      - environments/dev/postgres-values.yaml

  - name: pgadmin
    namespace: dev
    chart: runix/pgadmin4
    version: 1.18.0
    values:
      - environments/dev/pgadmin-values.yaml

  - name: vault
    namespace: dev
    chart: hashicorp/vault
    version: 0.27.0
    values:
      - values/vault-values.yaml