replicaCount: 1

installCRDs: true

image:
  repository: external-secrets/external-secrets
  tag: v0.9.2
  pullPolicy: IfNotPresent

rbac:
  create: true
  clusterWideAccess: false

provider:
  vault:
    server: "https://vault.java-mp.space"
    auth:
      kubernetes:
        mountPath: "auth/kubernetes"
        role: "pgadmin-role"

logLevel: info

admissionWebhook:
  enabled: true

ingress:
  enabled: false