env:
  existingSecret: pgadmin-secret
  emailSecretKey: PGADMIN_DEFAULT_EMAIL
  passwordSecretKey: PGADMIN_DEFAULT_PASSWORD

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: pgadmin.java-mp.space
      paths:
        - /
  tls:
    - secretName: pgadmin-tls
      hosts:
        - pgadmin.java-mp.space