apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: secret/data/pgadmin
        property: email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: secret/data/pgadmin
        property: password