image:
  registry: docker.io
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

auth:
  postgresPassword: ""
  database: "app_db"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: ClusterIP
  port: 5432