name: Deploy to K3s

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: Setup Helmfile
        run: |
          wget -O helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v0.157.0/helmfile_0.157.0_linux_amd64.tar.gz
          mkdir helmfile-bin
          tar -xzf helmfile.tar.gz -C helmfile-bin
          chmod +x helmfile-bin/helmfile
          sudo mv helmfile-bin/helmfile /usr/local/bin/

      - name: Helmfile Lint
        run: |
          cd helmfile
          helmfile -e dev lint
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/master'
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helmfile
        run: |
          wget -O helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v0.157.0/helmfile_0.157.0_linux_amd64.tar.gz
          mkdir helmfile-bin
          tar -xzf helmfile.tar.gz -C helmfile-bin
          chmod +x helmfile-bin/helmfile
          sudo mv helmfile-bin/helmfile /usr/local/bin/

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Tools
        run: |
          helm version
          helmfile version
          kubectl version --client

      - name: Setup Helm Diff Plugin
        run: |
          helm plugin install https://github.com/databus23/helm-diff || echo "Plugin already installed"

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Apply ClusterIssuer
        run: kubectl apply -f cert-manager/clusterissuer.yaml

      - name: Deploy to Dev
        run: |
          cd helmfile
          helmfile -e dev apply
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}