name: Deploy to K3s

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: Setup Helmfile
        run: |
          wget -O helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v0.157.0/helmfile_0.157.0_linux_amd64.tar.gz
          mkdir helmfile-bin
          tar -xzf helmfile.tar.gz -C helmfile-bin
          chmod +x helmfile-bin/helmfile
          sudo mv helmfile-bin/helmfile /usr/local/bin/

      - name: Validate Helm Charts
        run: |
          helm lint ./postgres

      - name: Helmfile Lint
        run: |
          helmfile lint

  deploy-dev:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/develop'
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          # Проверка версий уже установленных инструментов
          helm version
          helmfile version
          kubectl version --client

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Dev
        run: |
          helmfile -e dev apply
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}