name: Deploy to K3s

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: Setup Helmfile
        run: |
          wget -O helmfile.tar.gz https://github.com/helmfile/helmfile/releases/download/v0.157.0/helmfile_0.157.0_linux_amd64.tar.gz
          tar -xzf helmfile.tar.gz
          chmod +x helmfile
          sudo mv helmfile /usr/local/bin/

      - name: Validate Helm Charts
        run: |
          helm lint ./postgres

      - name: Helmfile Lint
        run: |
          cd helmfile
          helmfile lint

  deploy-dev:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/develop'
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          # Проверка версий уже установленных инструментов
          helm version
          helmfile version
          kubectl version --client

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Dev
        run: |
          cd helmfile
          helmfile -e dev apply
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          helm version
          helmfile version
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Production
        run: |
          cd helmfile
          helmfile -e prod apply
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_PROD }}